apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: velero
      image: "velero/velero:v1.9.3"
      imagePullPolicy: IfNotPresent
      command:
        - /tmp/sh
      args:
        - -c
        - /velero install --crds-only --dry-run -o yaml | /tmp/kubectl apply -f -
