apiVersion: networking.k8s.io/v1  
kind: Ingress  
metadata: 
 name: myingress
 annotations:
   kubernetes.io/ingress.class: nginx-private
spec:
  rules:
  - host: jenkins1-agent.monitoring.svc.cluster.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jenkins1
            port: 
              number: 8080
