apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  gcePersistentDisk:
    pdName: mongodb-disk1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc1
metadata:
  name: mongo-pvc1
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: mongo-pv1
  resources:
    requests:
      storage: 5Gi

