apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  gcePersistentDisk:
    pdName: mysql
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc1
metadata:
  name: mysql-pvc1
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: mysql-pv1
  resources:
    requests:
      storage: 5Gi
