apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: db
    name: mysql-pvc-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-0
spec:
  storageClassName: standard
  volumeName: mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
