apiVersion: v1
kind: Service
metadata:
  name: agent-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: jenkins-controller 
  ports:
    - port: 50000
      targetPort: 50000
      nodePort: 30050 
