apiVersion: v1
kind: Pod
metadata:
  name: test-pod-3
  namespace: default
spec:
  containers:
  - name: myubuntu
    image: docker.io/oshokumar/myubuntu:1
    command: ['sh','-c', 'sleep 999']
    securityContext:
       privileged: true
       allowPrivilegeEscalation: true
