kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: monitoring
 namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: monitoring
 namespace: monitoring
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: monitoring
subjects:
- kind: ServiceAccount
  name: monitoring
