apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mia
  namespace: new1
subjects:
- kind: User
  name: mia
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: list-deployments
  apiGroup: rbac.authorization.k8s.io
