apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: jenkins-controller 
  ports:
    - name: masterport
      port: 8080
      targetPort: 8080
      nodePort: 30080 
    - name: agentport
      port: 50000
      targetPort: 50000
      nodePort: 30050 
