apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: jenkins-controller 
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30380
